# Generated by Django 3.1.5 on 2021-01-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='metadata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
